[package]
name = "injection"
version = "0.1.0"
edition = "2021"

[lib]
name = "injection"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
ilhook.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
windows.workspace = true
