injection = "V:/Programming/Projects/lockdown_unlocked/target/i686-pc-windows-msvc/release/injection.dll"
lockdown_browser = "D:/Sandbox/LockdownBrowser/drive/C/Program Files (x86)/Respondus/LockDown Browser/LockDownBrowser.exe"
